#!/usr/bin/env python3
"""Generate worlds/apartment*.sdf plus the ArUco and poster models from config/apartment_layout.yaml.

The textures are drawn with OpenCV. Run from anywhere (needs the system OpenCV, not a pip one):
    PYTHONNOUSERSITE=1 python3 ros2_ws/src/jgb_rover_gazebo/scripts/gen_world.py
Outputs are written into the package source tree (worlds/ and models/) and are meant to be committed.
"""
import argparse
import math
from pathlib import Path

import cv2
import numpy as np
import yaml

PKG = Path(__file__).resolve().parent.parent


# --------------------------------------------------------------------------- textures
def aruco_dictionary(name: str):
    """OpenCV 4.5 (old API) and >= 4.7 (new API) compatible dictionary lookup."""
    dict_id = getattr(cv2.aruco, name)
    if hasattr(cv2.aruco, 'getPredefinedDictionary'):
        return cv2.aruco.getPredefinedDictionary(dict_id)
    return cv2.aruco.Dictionary_get(dict_id)


def aruco_image(dictionary, marker_id: int, cells: int, px_per_cell: int, margin_cells: int) -> np.ndarray:
    """Marker (cells x cells incl. black border) with a white quiet zone of margin_cells."""
    side = cells * px_per_cell
    if hasattr(cv2.aruco, 'generateImageMarker'):
        img = cv2.aruco.generateImageMarker(dictionary, marker_id, side)
    else:
        img = cv2.aruco.drawMarker(dictionary, marker_id, side)
    m = margin_cells * px_per_cell
    return cv2.copyMakeBorder(img, m, m, m, m, cv2.BORDER_CONSTANT, value=255)


def poster_image(seed: int, w_px: int, h_px: int) -> np.ndarray:
    """Colourful procedural poster: gradient, shapes and a title."""
    rng = np.random.default_rng(seed)
    c0, c1 = rng.integers(40, 255, 3), rng.integers(40, 255, 3)
    t = np.linspace(0.0, 1.0, w_px)[None, :, None]
    img = ((1 - t) * c0 + t * c1).repeat(h_px, axis=0).astype(np.uint8)
    for _ in range(12):
        colour = tuple(int(v) for v in rng.integers(0, 255, 3))
        if rng.random() < 0.5:
            centre = (int(rng.integers(0, w_px)), int(rng.integers(0, h_px)))
            cv2.circle(img, centre, int(rng.integers(10, h_px // 4)), colour, -1)
        else:
            p0 = (int(rng.integers(0, w_px)), int(rng.integers(0, h_px)))
            p1 = (p0[0] + int(rng.integers(20, w_px // 3)), p0[1] + int(rng.integers(20, h_px // 3)))
            cv2.rectangle(img, p0, p1, colour, -1)
    cv2.putText(img, f'POSTER {seed}', (20, h_px - 30), cv2.FONT_HERSHEY_DUPLEX, 1.6, (255, 255, 255), 4)
    return img


# --------------------------------------------------------------------------- sdf helpers
def rgba(c, a=1.0):
    return f'{c[0]} {c[1]} {c[2]} {a}'


def plain_material(colour) -> str:
    return (f'<material><ambient>{rgba(colour)}</ambient><diffuse>{rgba(colour)}</diffuse>'
            f'<specular>0.02 0.02 0.02 1</specular></material>')


def static_model(name, pose, geometry, colour, mu=None, collide=True) -> str:
    surface = ''
    if mu is not None:
        surface = (f'<surface><friction><ode><mu>{mu}</mu><mu2>{mu}</mu2></ode></friction></surface>')
    collision = (f'<collision name="collision"><geometry>{geometry}</geometry>{surface}</collision>'
                 if collide else '')
    return f'''
    <model name="{name}">
      <static>true</static>
      <pose>{pose}</pose>
      <link name="link">
        {collision}
        <visual name="visual"><geometry>{geometry}</geometry>{plain_material(colour)}</visual>
      </link>
    </model>'''


def textured_wall_model_dir(models_dir: Path, name: str, image: np.ndarray, size_wh) -> None:
    """A visual-only plane facing +x of the model frame, textured with image."""
    d = models_dir / name
    (d / 'materials' / 'textures').mkdir(parents=True, exist_ok=True)
    cv2.imwrite(str(d / 'materials' / 'textures' / f'{name}.png'), image)
    (d / 'model.config').write_text(f'''<?xml version="1.0"?>
<model>
  <name>{name}</name>
  <version>1.0</version>
  <sdf version="1.8">model.sdf</sdf>
  <description>Generated by gen_world.py</description>
</model>
''')
    (d / 'model.sdf').write_text(f'''<?xml version="1.0"?>
<sdf version="1.8">
  <model name="{name}">
    <static>true</static>
    <link name="link">
      <visual name="visual">
        <geometry><plane><normal>1 0 0</normal><size>{size_wh[0]} {size_wh[1]}</size></plane></geometry>
        <material>
          <ambient>1 1 1 1</ambient><diffuse>1 1 1 1</diffuse><specular>0 0 0 1</specular>
          <pbr><metal>
            <albedo_map>model://{name}/materials/textures/{name}.png</albedo_map>
            <roughness>1.0</roughness><metalness>0.0</metalness>
          </metal></pbr>
        </material>
      </visual>
    </link>
  </model>
</sdf>
''')


def include(name, pose) -> str:
    return f'''
    <include><uri>model://{name}</uri><name>{name}</name><pose>{pose}</pose></include>'''


def wall_item_pose(item, z, offset=0.002) -> str:
    yaw = item['normal_yaw']
    x = item['xy'][0] + offset * math.cos(yaw)
    y = item['xy'][1] + offset * math.sin(yaw)
    return f'{x:.4f} {y:.4f} {z:.4f} 0 0 {yaw}'


# --------------------------------------------------------------------------- world
def build_world(L: dict, models_dir: Path, with_slip: bool) -> str:
    parts = []
    fl = L['floor']
    parts.append(static_model(
        'floor', '0 0 0 0 0 0',
        f'<plane><normal>0 0 1</normal><size>{fl["size"][0]} {fl["size"][1]}</size></plane>',
        fl['color'], mu=fl['mu']))

    w = L['walls']
    for name, (cx, cy, lx, ly) in w['boxes'].items():
        parts.append(static_model(
            f'wall_{name}', f'{cx} {cy} {w["height"] / 2} 0 0 0',
            f'<box><size>{lx} {ly} {w["height"]}</size></box>', w['color']))

    for ob in L['obstacles']:
        z0 = ob.get('z_base', 0.0)
        yaw = ob.get('yaw', 0.0)
        if ob['type'] == 'box':
            sx, sy, sz = ob['size']
            geom = f'<box><size>{sx} {sy} {sz}</size></box>'
            zc = z0 + sz / 2
        elif ob['type'] == 'cylinder':
            geom = f'<cylinder><radius>{ob["radius"]}</radius><length>{ob["height"]}</length></cylinder>'
            zc = z0 + ob['height'] / 2
        else:
            raise ValueError(f'unknown obstacle type {ob["type"]}')
        parts.append(static_model(ob['name'], f'{ob["xy"][0]} {ob["xy"][1]} {zc} 0 0 {yaw}', geom, ob['color']))

    if with_slip:
        sp = L['slip_patches']
        for i, p in enumerate(sp['items']):
            parts.append(static_model(
                f'slip_patch_{i}', f'{p["xy"][0]} {p["xy"][1]} 0.0005 0 0 0',
                f'<box><size>{p["size"][0]} {p["size"][1]} 0.001</size></box>', fl['color'], mu=sp['mu']))

    po = L['posters']
    w_px = 512
    h_px = int(round(w_px * po['size'][1] / po['size'][0]))
    for item in po['items']:
        textured_wall_model_dir(models_dir, item['name'], poster_image(item['seed'], w_px, h_px), po['size'])
        parts.append(include(item['name'], wall_item_pose(item, po['z_centre'])))

    ar = L['aruco']
    dictionary = aruco_dictionary(ar['dictionary'])
    bits = int(ar['dictionary'].split('_')[1][0])          # DICT_4X4_50 -> 4
    cells = bits + 2                                         # + black border
    margin = 1                                               # white quiet zone, cells
    cell_m = ar['marker_size'] / cells
    plane = (cells + 2 * margin) * cell_m
    for item in ar['items']:
        name = f'aruco_marker_{item["id"]}'
        img = aruco_image(dictionary, item['id'], cells, ar['texture_px_per_cell'], margin)
        textured_wall_model_dir(models_dir, name, img, (plane, plane))
        parts.append(include(name, wall_item_pose(item, ar['z_centre'])))

    lt = L['lighting']
    shadows = 'true' if lt['cast_shadows'] else 'false'
    return f'''<?xml version="1.0"?>
<!-- GENERATED by scripts/gen_world.py from config/apartment_layout.yaml. Do not edit by hand. -->
<sdf version="1.8">
  <world name="{L['world_name']}">
    <physics name="1ms" type="ignored">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin filename="ignition-gazebo-physics-system" name="ignition::gazebo::systems::Physics"/>
    <plugin filename="ignition-gazebo-user-commands-system" name="ignition::gazebo::systems::UserCommands"/>
    <plugin filename="ignition-gazebo-scene-broadcaster-system" name="ignition::gazebo::systems::SceneBroadcaster"/>
    <plugin filename="ignition-gazebo-sensors-system" name="ignition::gazebo::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="ignition-gazebo-imu-system" name="ignition::gazebo::systems::Imu"/>

    <scene>
      <ambient>{rgba(lt['ambient'])}</ambient>
      <background>0.85 0.85 0.82 1</background>
      <shadows>{shadows}</shadows>
      <grid>false</grid>
    </scene>

    <light type="directional" name="sun">
      <cast_shadows>{shadows}</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.8 0.8 0.8 1</diffuse>
      <specular>0.1 0.1 0.1 1</specular>
      <direction>-0.3 0.2 -0.9</direction>
    </light>
{''.join(parts)}
  </world>
</sdf>
'''


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--layout', default=str(PKG / 'config' / 'apartment_layout.yaml'))
    args = ap.parse_args()
    layout = yaml.safe_load(Path(args.layout).read_text())
    models_dir = PKG / 'models'
    worlds_dir = PKG / 'worlds'
    worlds_dir.mkdir(exist_ok=True)
    name = layout['world_name']
    (worlds_dir / f'{name}.sdf').write_text(build_world(layout, models_dir, with_slip=False))
    slip = dict(layout, world_name=f'{name}_slip')
    (worlds_dir / f'{name}_slip.sdf').write_text(build_world(slip, models_dir, with_slip=True))
    print(f'wrote {worlds_dir}/{name}.sdf, {name}_slip.sdf and {len(list(models_dir.iterdir()))} models')


if __name__ == '__main__':
    main()
